### Importação de Bibliotecas

In [1]:
import pandas as pd
import pathlib
import win32com.client as win32

### Importação e Leitura das Bases de Dados

In [2]:
df_emails = pd.read_excel(r'Bases de Dados/Emails.xlsx')
df_lojas = pd.read_csv(r'Bases de Dados/Lojas.csv', sep=';', encoding='latin')
df_vendas = pd.read_excel(r'Bases de Dados/Vendas.xlsx')

display(df_emails.head())
display(df_lojas.head())
display(df_vendas.head())

,Loja,Gerente,E-mail
0,Iguatemi Esplanada,Helena,paraprojetosautoma+Helena@outlook.com
1,Shopping Midway Mall,Alice,paraprojetosautoma+Alice@outlook.com
2,Norte Shopping,Laura,paraprojetosautoma+Laura@outlook.com
3,Shopping Iguatemi Fortaleza,Manuela,paraprojetosautoma+Manuela@outlook.com
4,Shopping União de Osasco,Valentina,paraprojetosautoma+Valentina@outlook.com

   ID Loja                         Loja
0        1           Iguatemi Esplanada
1        2         Shopping Midway Mall
2        3               Norte Shopping
3        4  Shopping Iguatemi Fortaleza
4        5     Shopping União de Osasco

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,1,2019-01-01,1,Sapato Estampa,1,358,358
1,1,2019-01-01,1,Camiseta,2,180,360
2,1,2019-01-01,1,Sapato Xadrez,1,368,368
3,2,2019-01-02,3,Relógio,3,200,600
4,2,2019-01-02,3,Chinelo Liso,1,71,71

In [5]:
print(df_vendas.info())
print(df_lojas.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100999 entries, 0 to 100998
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Código Venda    100999 non-null  int64
 1   Data            100999 non-null  datetime64[ns]
 2   ID Loja         100999 non-null  int64
 3   Produto         100999 non-null  object
 4   Quantidade      100999 non-null  int64
 5   Valor Unitário  100999 non-null  int64
 6   Valor Final     100999 non-null  int64
dtypes: datetime64[ns](1), int64(5), object(1)
memory usage: 5.4+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   ID Loja  25 non-null     int64
 1   Loja     25 non-null     object
dtypes: int64(1), object(1)
memory usage: 532.0+ bytes
None

### Criação de um dataframe que mescle as informações de vendas e lojas

In [ ]:
# Cria o df mesclando as informações de vendas e lojas
df_vendas_lojas = df_vendas.merge(df_lojas, on='ID Loja')
print(df_vendas_lojas.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100999 entries, 0 to 100998
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Código Venda    100999 non-null  int64
 1   Data            100999 non-null  datetime64[ns]
 2   ID Loja         100999 non-null  int64
 3   Produto         100999 non-null  object
 4   Quantidade      100999 non-null  int64
 5   Valor Unitário  100999 non-null  int64
 6   Valor Final     100999 non-null  int64
 7   Loja            100999 non-null  object
dtypes: datetime64[ns](1), int64(5), object(2)
memory usage: 6.2+ MB
None

### Salvar planilha de cada loja na pasta de backup

In [7]:
# cria um dataframe para armazenar {'nome_loja': df_da_loja}

dicionario_info_lojas = {} 

# preenche o dicionario 

for loja in df_lojas['Loja']: # percorre o a coluna 'Loja' do df das lojas
    dicionario_info_lojas[loja] = df_vendas_lojas.loc[df_vendas_lojas['Loja']==loja,:]
    ''' cria um item no dicionario com o nome da loja e o df com as vendas referentes a loja 
       a partir completo(mesclado) de vendas e lojas '''
display(dicionario_info_lojas['Iguatemi Esplanada'])

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final,Loja
0,1,2019-01-01,1,Sapato Estampa,1,358,358,Iguatemi Esplanada
1,1,2019-01-01,1,Camiseta,2,180,360,Iguatemi Esplanada
2,1,2019-01-01,1,Sapato Xadrez,1,368,368,Iguatemi Esplanada
26,21,2019-01-02,1,Camisa Gola V Listrado,2,116,232,Iguatemi Esplanada
44,34,2019-01-02,1,Sapato Listrado,1,363,363,Iguatemi Esplanada
...,...,...,...,...,...,...,...,...
100847,69899,2019-12-25,1,Sapato Xadrez,4,368,1472,Iguatemi Esplanada
100854,69903,2019-12-25,1,Terno Liso,5,720,3600,Iguatemi Esplanada
100894,69928,2019-12-25,1,Meia,1,30,30,Iguatemi Esplanada
100920,69944,2019-12-25,1,Gorro Xadrez,5,85,425,Iguatemi Esplanada
100921,69944,2019-12-25,1,Sapato Xadrez,2,368,736,Iguatemi Esplanada

### Definir o dia do indicador

In [8]:
dia_calculo_indicador = df_vendas_lojas['Data'].max() # mantém o cálculo do indicador atualizado

print(dia_calculo_indicador)

2019-12-26 00:00:00

### Criar uma tabela para cada loja

In [10]:
caminho_backup = pathlib.Path(r'Backup Arquivos Lojas') # coloca em uma variavel o caminho a ser percorrido

arquivos_pasta_backup = caminho_backup.iterdir() # pega todos os arquivos que tem no caminho

lista_nome_arquivos = [arquivo.name for arquivo in arquivos_pasta_backup] # cria uma lista com o nome dos arquivos

for loja in dicionario_info_lojas: # verifica se a pasta existe, cria se nao existir, e armazena os arquivos em suas respectivas pastas
    if loja not in lista_nome_arquivos: # verifica se NAO existe a pasta referente a loja
        nova_pasta = caminho_backup/loja # define a localizacao e nome da pasta 
        nova_pasta.mkdir() # cria a pasta

    nome_arquivo = f'{dia_calculo_indicador.month}_{dia_calculo_indicador.day}_{loja}.xlsx' # nome do arquivo

    local_armazen_arquivo = caminho_backup / loja / nome_arquivo # variavel que armazena o caminho completo do ARQUIVO

    dicionario_info_lojas[loja].to_excel(local_armazen_arquivo) #gera o arquivo excel com cada dataframe do dicionario.

### Definição das Metas Pré Estabelecidas

In [9]:
#definição de metas

meta_faturamento_dia = 1000
meta_faturamento_ano = 1650000
meta_qtdeprodutos_dia = 4
meta_qtdeprodutos_ano = 120
meta_ticketmedio_dia = 500
meta_ticketmedio_ano = 500

### Cálculo de indicadores e disparo de e-mail para cada loja da rede.

In [11]:
for loja in dicionario_info_lojas:

    # cria-se um dataframe auxiliar filtrando pela data para o calculo dos indicadores diários

    df_aux_vendas_lojas_dia = dicionario_info_lojas[loja].loc[dicionario_info_lojas[loja]['Data']==dia_calculo_indicador, :]
    # faturamento - somar valor das vendas de cada loja
    faturamento_ano = dicionario_info_lojas[loja]['Valor Final'].sum()
    faturamento_dia = df_aux_vendas_lojas_dia['Valor Final'].sum()

    # diversidade de produtos vendidos:
    div_prod_vend_ano = dicionario_info_lojas[loja]['Produto'].nunique() #conta o numero de valores unicos
    div_prod_vend_dia = df_aux_vendas_lojas_dia['Produto'].nunique()

    # ticket medio por venda:
    # criam-se df auxiliares com agrupamento por codigo de venda para o calculo do ticket medio por venda.
    df_aux_agroup_por_vendas_ano = dicionario_info_lojas[loja].groupby('Código Venda').sum(numeric_only=True).sort_values(by='Código Venda')
    df_aux_agroup_por_vendas_dia = df_aux_vendas_lojas_dia.groupby('Código Venda').sum(numeric_only=True).sort_values(by='Código Venda')

    tkt_med_ano = df_aux_agroup_por_vendas_ano['Valor Final'].mean()
    tkt_med_dia = df_aux_vendas_lojas_dia['Valor Final'].mean()

        #enviar o e-mail
    outlook = win32.Dispatch('outlook.application')

    nome = df_emails.loc[df_emails['Loja']==loja, 'Gerente'].values[0]
    mail = outlook.CreateItem(0)
    mail.To = df_emails.loc[df_emails['Loja']==loja, 'E-mail'].values[0]
    mail.Subject = f'OnePage Dia {dia_calculo_indicador.day}/{dia_calculo_indicador.month} - Loja {loja}'
    #mail.body = 'Texto do E-mail'

    if faturamento_dia >= meta_faturamento_dia:
            cor_fat_dia = 'green'
    else:
        cor_fat_dia = 'red'
    if faturamento_ano >= meta_faturamento_ano:
        cor_fat_ano = 'green'
    else:
        cor_fat_ano = 'red'
    if div_prod_vend_dia >= meta_qtdeprodutos_dia:
        cor_qtde_dia = 'green'
    else:
        cor_qtde_dia = 'red'
    if div_prod_vend_ano >= meta_qtdeprodutos_ano:
        cor_qtde_ano = 'green'
    else:
        cor_qtde_ano = 'red'
    if tkt_med_dia >= meta_ticketmedio_dia:
        cor_ticket_dia = 'green'
    else:
        cor_ticket_dia = 'red'
    if tkt_med_ano >= meta_ticketmedio_ano:
        cor_ticket_ano = 'green'
    else:
        cor_ticket_ano = 'red'

    mail.HTMLBody = f'''
    <p>Bom dia, {nome}</p>

    <p>O resultado de ontem <strong>({dia_calculo_indicador.day}/{dia_calculo_indicador.month})</strong> da <strong>Loja {loja}</strong> foi:</p>

    <table>
        <tr>
        <th>Indicador</th>
        <th>Valor Dia</th>
        <th>Meta Dia</th>
        <th>Cenário Dia</th>
        </tr>
        <tr>
        <td>Faturamento</td>
        <td style="text-align: center">R${faturamento_dia:.2f}</td>
        <td style="text-align: center">R${meta_faturamento_dia:.2f}</td>
        <td style="text-align: center"><font color="{cor_fat_dia}">◙</font></td>
        </tr>
        <tr>
        <td>Diversidade de Produtos</td>
        <td style="text-align: center">{div_prod_vend_dia}</td>
        <td style="text-align: center">{meta_qtdeprodutos_dia}</td>
        <td style="text-align: center"><font color="{cor_qtde_dia}">◙</font></td>
        </tr>
        <tr>
        <td>Ticket Médio</td>
        <td style="text-align: center">R${tkt_med_dia:.2f}</td>
        <td style="text-align: center">R${meta_ticketmedio_dia:.2f}</td>
        <td style="text-align: center"><font color="{cor_ticket_dia}">◙</font></td>
        </tr>
    </table>
    <br>
    <table>
        <tr>
        <th>Indicador</th>
        <th>Valor Ano</th>
        <th>Meta Ano</th>
        <th>Cenário Ano</th>
        </tr>
        <tr>
        <td>Faturamento</td>
        <td style="text-align: center">R${faturamento_ano:.2f}</td>
        <td style="text-align: center">R${meta_faturamento_ano:.2f}</td>
        <td style="text-align: center"><font color="{cor_fat_ano}">◙</font></td>
        </tr>
        <tr>
        <td>Diversidade de Produtos</td>
        <td style="text-align: center">{div_prod_vend_ano}</td>
        <td style="text-align: center">{meta_qtdeprodutos_ano}</td>
        <td style="text-align: center"><font color="{cor_qtde_ano}">◙</font></td>
        </tr>
        <tr>
        <td>Ticket Médio</td>
        <td style="text-align: center">R${tkt_med_ano:.2f}</td>
        <td style="text-align: center">R${meta_ticketmedio_ano:.2f}</td>
        <td style="text-align: center"><font color="{cor_ticket_ano}">◙</font></td>
        </tr>
    </table>

    <p>Segue em anexo a planilha com todos os dados para mais detalhes.</p>

    <p>Qualquer dúvida estou à disposição.</p>
    <p>Att., Igor</p>
    '''


    # Anexos (pode colocar quantos quiser):
    attachment  = pathlib.Path.cwd() / caminho_backup / loja / f'{dia_calculo_indicador.month}_{dia_calculo_indicador.day}_{loja}.xlsx'
    mail.Attachments.Add(str(attachment))

    mail.Send()
    

print('E-mails enviados')

E-mails enviados

### Criação de Ranking para a Diretoria

In [17]:
df_faturamento_anual_loja = df_vendas_lojas.groupby('Loja').sum(numeric_only=True).sort_values(by='Valor Final', ascending=False)
df_faturamento_diario_loja = df_vendas_lojas.loc[df_vendas_lojas['Data']==dia_calculo_indicador,:].groupby('Loja').sum(numeric_only=True).sort_values(by='Valor Final', ascending=False)
display(df_faturamento_anual_loja)
display(df_faturamento_diario_loja)

,Código Venda,ID Loja,Quantidade,Valor Unitário,Valor Final
Loja,,,,,
Iguatemi Campinas,145499790,98592,8935,796153,1762419
Shopping Vila Velha,152476000,80446,9224,803333,1731167
Bourbon Shopping SP,142577669,57624,8863,791748,1726110
Rio Mar Recife,149070473,28693,8863,798866,1722766
Shopping SP Market,143767529,81600,8927,788086,1721763
Palladium Shopping Curitiba,145545401,63150,9091,796103,1721120
Norte Shopping,145499571,12537,9014,798860,1711968
Ribeirão Shopping,140189391,44528,8825,786547,1707122
Iguatemi Esplanada,138859203,3980,8580,775886,1699681
Rio Mar Shopping Fortaleza,141379782,37062,8937,788921,1698430
Shopping Center Leste Aricanduva,142051349,40930,8938,772549,1682870
Novo Shopping Ribeirão Preto,140372814,93127,8751,773200,1678225
Shopping Iguatemi Fortaleza,139929886,16084,8629,776851,1674824
Center Shopping Uberlândia,138457517,68221,8627,774418,1668921
Shopping União de Osasco,140465649,19975,8730,768268,1663770
Shopping Barra,137802790,99050,8638,764265,1653103
Passei das Águas Shopping,139017557,64000,8618,768205,1649014
Shopping Eldorado,140673367,84042,8719,763800,1648111
Salvador Shopping,142839770,32240,8698,766808,1646739
Shopping Center Interlagos,139838616,24126,8675,769152,1640486
Shopping Ibirapuera,139728506,89122,8723,762115,1635060
Parque Dom Pedro Shopping,136735963,50726,8388,762457,1631630
Shopping Recife,135149305,70038,8581,746038,1624879
Shopping Midway Mall,132268359,7674,8206,738876,1590441
Shopping Morumbi,137023173,47520,8508,746266,1586444

,Código Venda,ID Loja,Quantidade,Valor Unitário,Valor Final
Loja,,,,,
Salvador Shopping,139944,16,8,1078,3950
Novo Shopping Ribeirão Preto,419914,138,15,1166,3400
Center Shopping Uberlândia,349970,85,12,929,2651
Shopping Eldorado,139972,42,7,775,2391
Shopping Center Interlagos,139956,12,4,791,1582
Shopping Recife,209924,54,6,683,1366
Norte Shopping,139952,6,5,509,1259
Shopping União de Osasco,209937,15,6,553,1207
Shopping Vila Velha,209929,57,7,450,937
Bourbon Shopping SP,69987,14,4,169,676
Ribeirão Shopping,209978,33,7,310,650
Shopping Center Leste Aricanduva,139950,20,6,221,485
Palladium Shopping Curitiba,139963,30,3,340,381
Rio Mar Shopping Fortaleza,69993,9,1,368,368
Shopping Midway Mall,69994,2,1,170,170
Shopping Ibirapuera,69977,22,1,118,118

In [ ]:
df_faturamento_anual_loja = df_faturamento_anual_loja.reset_index()
df_faturamento_anual_loja = df_faturamento_anual_loja.loc[:,['Loja','Valor Final']]

nome_arquivo = f'{dia_calculo_indicador.month}_{dia_calculo_indicador.day}_Ranking Anual.xlsx' # nome do arquivo

local_armazen_arquivo = caminho_backup / nome_arquivo # variavel que armazena o caminho completo do ARQUIVO

df_faturamento_anual_loja.to_excel(local_armazen_arquivo) 

df_faturamento_diario_loja = df_faturamento_diario_loja.reset_index()
df_faturamento_diario_loja = df_faturamento_diario_loja.loc[:,['Loja','Valor Final']]

nome_arquivo = f'{dia_calculo_indicador.month}_{dia_calculo_indicador.day}_Ranking Diario.xlsx' # nome do arquivo

local_armazen_arquivo = caminho_backup / nome_arquivo # variavel que armazena o caminho completo do ARQUIVO

df_faturamento_diario_loja.to_excel(local_armazen_arquivo) #transforma o df em um arquivo excel e armazena no caminho definido

display(df_faturamento_anual_loja)
display(df_faturamento_diario_loja)

                                Loja  Valor Final
0                  Iguatemi Campinas      1762419
1                Shopping Vila Velha      1731167
2                Bourbon Shopping SP      1726110
3                     Rio Mar Recife      1722766
4                 Shopping SP Market      1721763
5        Palladium Shopping Curitiba      1721120
6                     Norte Shopping      1711968
7                  Ribeirão Shopping      1707122
8                 Iguatemi Esplanada      1699681
9         Rio Mar Shopping Fortaleza      1698430
10  Shopping Center Leste Aricanduva      1682870
11      Novo Shopping Ribeirão Preto      1678225
12       Shopping Iguatemi Fortaleza      1674824
13        Center Shopping Uberlândia      1668921
14          Shopping União de Osasco      1663770
15                    Shopping Barra      1653103
16         Passei das Águas Shopping      1649014
17                 Shopping Eldorado      1648111
18                 Salvador Shopping      1646739
19        Shopping Center Interlagos      1640486
20               Shopping Ibirapuera      1635060
21         Parque Dom Pedro Shopping      1631630
22                   Shopping Recife      1624879
23              Shopping Midway Mall      1590441
24                  Shopping Morumbi      1586444

                                Loja  Valor Final
0                  Salvador Shopping         3950
1       Novo Shopping Ribeirão Preto         3400
2         Center Shopping Uberlândia         2651
3                  Shopping Eldorado         2391
4         Shopping Center Interlagos         1582
5                    Shopping Recife         1366
6                     Norte Shopping         1259
7           Shopping União de Osasco         1207
8                Shopping Vila Velha          937
9                Bourbon Shopping SP          676
10                 Ribeirão Shopping          650
11  Shopping Center Leste Aricanduva          485
12       Palladium Shopping Curitiba          381
13        Rio Mar Shopping Fortaleza          368
14              Shopping Midway Mall          170
15               Shopping Ibirapuera          118

In [24]:
print(df_faturamento_diario_loja.iloc[0, 1])
print(df_faturamento_diario_loja.index[0])

3950
0

### Envio de E-mail para a Diretoria

In [25]:
    #enviar o e-mail
outlook = win32.Dispatch('outlook.application')

mail = outlook.CreateItem(0)
mail.To = df_emails.loc[df_emails['Loja']=='Diretoria', 'E-mail'].values[0]
mail.Subject = f'Ranking Dia {dia_calculo_indicador.day}/{dia_calculo_indicador.month}'
mail.body = f'''
Prezados, bom dia

Melhor loja do Dia em Faturamento: Loja {df_faturamento_diario_loja.iloc[0, 0]} com Faturamento R${df_faturamento_diario_loja.iloc[0, 1]:.2f}
Pior loja do Dia em Faturamento: Loja {df_faturamento_diario_loja.iloc[-1, 1]} com Faturamento R${df_faturamento_diario_loja.iloc[-1, 1]:.2f}

Melhor loja do Ano em Faturamento: Loja {df_faturamento_anual_loja.iloc[0, 0]} com Faturamento R${df_faturamento_anual_loja.iloc[0, 1]:.2f}
Pior loja do Ano em Faturamento: Loja {df_faturamento_anual_loja.iloc[-1, 1]} com Faturamento R${df_faturamento_anual_loja.iloc[-1, 1]:.2f}

Segue em anexo os rankings do ano e do dia de todas as lojas.

Qualquer dúvida estou à disposição.


Att., Igor
'''
# Anexos (pode colocar quantos quiser):
attachment  = pathlib.Path.cwd() / caminho_backup / f'{dia_calculo_indicador.month}_{dia_calculo_indicador.day}_Ranking Diario.xlsx'
mail.Attachments.Add(str(attachment))

attachment  = pathlib.Path.cwd() / caminho_backup / f'{dia_calculo_indicador.month}_{dia_calculo_indicador.day}_Ranking Anual.xlsx'
mail.Attachments.Add(str(attachment))

mail.Send()


print('E-mail enviados')

E-mail enviados